### ISSUE TITLE
[Linux] Connecting to server using Wine

### ISSUE THREAD

**Issue by MadByteDE** [Make-Tarkov-Great-Again/MTGA-Backend#101]
Hey,

I'm on Linux using wine / proton / lutris to run the game (works well unmodified / with BepInEx installed but no plugins). 

I installed BepInEx sucessfully (config dir etc created, getting log files) and installed the plugin as well as nvm, node.js and the server. 

I had to change the port of the server to something else since (as stated in the readme) I'd need admin privilege which is a bit tricky on Linux using the Steam Deck. 

Now when launching the game it closes immediately and I assume I have to set the correct port for the client. How can I do that? Or may I have another issue? I got so far, I hope it can work on Linux :D

[Here is the error in the log file.](https://gist.github.com/MadByteDE/8f49bd2ae7434eb83c40736f4f1329c7)

![](https://i.imgur.com/U37TowM.png)

Thanks!

**Comment by SlejmUr** [comment]
You are just running the exe or from the webinterface?
Because the exe need a parameters to actually connect to server and so on

**Comment by MadByteDE** [comment]
> You are just running the exe or from the webinterface? Because the exe need a parameters to actually connect to server and so on

hadn't seen there is an web interface, thanks for the hint. I "registered" in it now, but launching from here won't be possible out of the box. I'll look into the code to see if there is a way to launch my specific command to pipe the parameters to. But I guess there is some code needed server-side to do it properly on such a nich setup as mine. 

Would it be possible to display the specific parameters the client would get from the server to manually append them? I'll look into it as well. Thanks so far!

**Comment by MadByteDE** [comment]
Found it:
```js
exec(tarkovPath + ' -bC5vLmcuaS5u={"email":"' + userAccount.email + '","password":"' + userAccount.password + '","toggle":true,"timestamp":0} -token=' + sessionID + ' -config={"BackendUrl":"https://' + ip + ':' + port + '","Version":"live"}');
```

I'll play around with it a bit. Thanks.

**Comment by MadByteDE** [comment]
Okay, I actually managed to append my modified parameter arguments successfully, but I potentially don't have the correct session id since when connect it works but the game menu is just blank, no buttons - just the background. I tried to use the "session id" I could find in the server console when connecting with my profile, but I believe this is not the right one ?

**Comment by SlejmUr** [comment]
Are you using the develop branch?

**Comment by MadByteDE** [comment]
> Are you using the develop branch?

In `settings` "Developer" is selected yes. Changing to "Edge of Darkness" doesn't seem to change anything either.

**Comment by MadByteDE** [comment]
> Are you using the develop branch?

It works with the develop branch!

Thanks.. :+1:

**Comment by SlejmUr** [comment]
No problem,

Have fun!
