### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MadByteDE** [Make-Tarkov-Great-Again/MTGA-Backend#102]
Hi,

Info:
**OS**: SteamOS 3.4 (Linux)
**Version**: develop branch (commit [790e563](https://github.com/Make-Tarkov-Great-Again/MTGA-Backend/commit/790e563964703b2c4ccc123385fcaff90924a646))

sadly I have another issue when starting a play session:

![](https://i.imgur.com/SgN8xy6.jpg)

Seems to happen on all maps.

Any idea what to to with this?

Thanks!

EDIT:
Possibly related to https://github.com/Make-Tarkov-Great-Again/MTGA-Backend/discussions/92#discussioncomment-4820169 ?

**Comment by Nehaxfr** [comment]
Probably bot gen related.

Trying to do a normal playthrough with the current state of the backend will only result in errors, I suggest that you wait for a potential release.
