### ISSUE TITLE
|0.13.0.3.22173|Error|FilesChecker|Consistency ensurance failed. File not exist. File: "EscapeFromTarkov_BE.exe". ElapsedMilliseconds:115 

### ISSUE THREAD

**Issue by 3r70rp1zh31p** [Make-Tarkov-Great-Again/MTGA-Backend#104]
I followed the instructions and it closes after a quick black screen

**Comment by TheUnrealUnicorn** [comment]
Did you accept the licence?

**Comment by 3r70rp1zh31p** [comment]
> Did you accept the licence?
where would i find that?

**Comment by TheUnrealUnicorn** [comment]
When you start the server you get a pop up to accept the licence bro

**Comment by 3r70rp1zh31p** [comment]
theres a server i need to start?

**Comment by 3r70rp1zh31p** [comment]
oh i see it

**Comment by TheUnrealUnicorn** [comment]
1.Prepare your client:
https://github.com/Make-Tarkov-Great-Again/MTGA-Backend/wiki/How-To-Prepare-your-Client

2.Follow the instructions to setup your server:
https://github.com/Make-Tarkov-Great-Again/MTGA-Backend/wiki/Installing-and-running-the-MTGA-Server-on-Linux-and-Windows.

**Comment by 3r70rp1zh31p** [comment]
still happening

**Comment by 3r70rp1zh31p** [comment]
it looks like a file checker its trying to find the battle eye files

**Comment by ae-King** [comment]
Your client has not been prepared properly.

**Comment by 3r70rp1zh31p** [comment]
i don't get what im missing i followed the instructions

**Comment by ae-King** [comment]
> i don't get what im missing i followed the instructions

You followed them but incorrectly.

**Comment by 3r70rp1zh31p** [comment]
i copied the Tarkov files to a different directory then installed bepinex then started it to install bepinex files then put the 2 dll files where they need to go then got the server installed and running

**Comment by 3r70rp1zh31p** [comment]
got it sorry im new to all this didnt know i needed to go to the server website and launch it from there

**Comment by ae-King** [comment]
> got it sorry im new to all this didnt know i needed to go to the server website and launch it from there

Ah, yeah. I should put a prompt but we hope in the future an external launcher is developed.
