### ISSUE TITLE
Request body size did not match Content-Length

### ISSUE THREAD

**Issue by 3r70rp1zh31p** [Make-Tarkov-Great-Again/MTGA-Backend#105]
![image](https://user-images.githubusercontent.com/106615083/227380892-cbfe44f2-9b3a-4494-8286-528fb89fb680.png)

**Comment by 3r70rp1zh31p** [comment]
man im having alot of issue today

**Comment by 3r70rp1zh31p** [comment]
it also gives me a warning saying bundles not implemented yet don't know its thats a bad thing or not

**Comment by 3r70rp1zh31p** [comment]
fixed it by updating to devloper edition but now im getting alot more errors than i think im supposed to be getting and i can't even play

**Comment by Nehaxfr** [comment]
Game version ?
What branch of the server repo are you running ?
