### ISSUE TITLE
Trader filtered assort on loyalty

### ISSUE THREAD

**Issue by Nehaxfr** [Make-Tarkov-Great-Again/MTGA-Backend#6]
Retrieve trader assort based on player data:
- player loyalty,
Retrieve stash sellable items & prices

**Comment by Nehaxfr** [comment]
Need to complet quests implementation before moving further in the filtering of assorts

**Comment by Nehaxfr** [comment]
Issue with stock probably

![Image](https://user-images.githubusercontent.com/74174676/178083942-421bb7f4-0e91-44b0-b938-8d5f917c00a3.png)

**Comment by ae-King** [comment]
you fool

**Comment by Nehaxfr** [comment]
Fixed issue with qty, guns being sold in kits and undefined prices
