### ISSUE TITLE
no taxonomy node found

### ISSUE THREAD

**Issue by Ultra119** [Make-Tarkov-Great-Again/MTGA-Backend#86]
Logs:
https://pastebin.com/hH2Xsamz

Version: 0.12.12.32.19904
MTGA bin version: Release

**Comment by ae-King** [comment]
Which branch are you using?

**Comment by Ultra119** [comment]
> Which branch are you using?

main

**Comment by Ultra119** [comment]
> > 
> 
> Update your Live Client to latest.

In short, it helped. But there was another problem (or maybe it was), some bots spin in one place and shoot through the walls, even though the enemy is not in sight and far away. Well, in general, they are kind of dull, if you compare with JET or AKI

**Comment by ae-King** [comment]
> In short, it helped. But there was another problem (or maybe it was), some bots spin in one place and shoot through the walls, even though the enemy is not in sight and far away. Well, in general, they are kind of dull, if you compare with JET or AKI

Bot difficulties are directly pulled from Live, and haven't been modified. I am unsure if AKI is using some tweaks that Fin did before they left. JET uses difficulties from Altered Escape as that was the base used for the latest release.

**Comment by Ultra119** [comment]
> > In short, it helped. But there was another problem (or maybe it was), some bots spin in one place and shoot through the walls, even though the enemy is not in sight and far away. Well, in general, they are kind of dull, if you compare with JET or AKI
> 
> Bot difficulties are directly pulled from Live, and haven't been modified. I am unsure if AKI is using some tweaks that Fin did before they left. JET uses difficulties from Altered Escape as that was the base used for the latest release.

Also the items are too light. Is this also on the client side? For example, this AK, in reality it weighs 4kg, and that's without additional attachments. Can I change the weight of all items?
![image](https://user-images.githubusercontent.com/64977575/200656589-dcf373f8-1d34-499b-881f-d5b4d979005c.png)

**Comment by Ultra119** [comment]
next problem))) Trying to buy any weapon from any merchant, with other items does not seem to be the same. There is space in the inventory, of course
```
[DEBUG] 2022-11-08 19:31:35 [tradingConfirm] [object Object]
[DEBUG] 2022-11-08 19:31:35
Item {
  _id: '5fe49a0e2694b0755a5047ae',
  _tpl: '55d4887d4bdc2d962f8b4570',
  parentId: '61b7367440281631fc83f17c',
  slotId: 'hideout',
  location: { x: 9, y: 3, r: 'Horizontal', isSearched: true }
}
[ERROR] 2022-11-08 19:31:35 Inventory item occupies invalid slot: _id: 5fe49a0e2694b0755a5047ae _tpl: 55d4887d4bdc2d962f8b4570 parentId: 61b7367440281631fc83f17c slotId: hideout y: 3 x: 10 - width: 2 height: 1
[DEBUG] 2022-11-08 19:31:35 Unable to add item 57c44b372459772d2b39b8ce. No space.
[DEBUG] 2022-11-08 19:31:35
undefined
[21:31:35.024] INFO (4872): incoming request {"reqId":"req-28","req":"[POST] /client/game/profile/items/moving"}
[21:31:35.035] ERROR (4872): Cannot read properties of undefined (reading 'getAllChildItemsInInventory') {"reqId":"req-28","req":"[POST] /client/game/profile/items/moving","res":"500"}
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'getAllChildItemsInInventory')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'getAllChildItemsInInventory')
              at Character.removeItem (C:\MTGA-Backend-main\lib\models\Character.js:565:37)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Character.addItem (C:\MTGA-Backend-main\lib\models\Character.js:447:21)
              at async TraderController.buyFromTrader (C:\MTGA-Backend-main\lib\controllers\TraderController.js:169:26)
              at async TraderController.tradingConfirm (C:\MTGA-Backend-main\lib\controllers\TraderController.js:115:21)
              at async Object.<anonymous> (C:\MTGA-Backend-main\routes\client\Profile.js:156:36)
    }
```

**Comment by pixelkingliam** [comment]
This could be a config option, considering that the armored rig w/ vest option came from a mod, a mod also existed to reduce item weight so it possible this was integrated, this is prob a modifier somewhere

**Comment by ae-King** [comment]
Do you have a way to replicate it? As far as the debug log goes, it seems like there's no space in your stash.

**Comment by Ultra119** [comment]
> Do you have a way to replicate it? As far as the debug log goes, it seems like there's no space in your stash.

I could even record a video, but I don't think it would be comfortable to upload it here, so it's better to continue on telegram @Ultra119

**Comment by ae-King** [comment]
> > Do you have a way to replicate it? As far as the debug log goes, it seems like there's no space in your stash.
> 
> I could even record a video, but I don't think it would be comfortable to upload it here, so it's better to continue on telegram @Ultra119

Is your inventory full?

**Comment by Ultra119** [comment]
> > > Do you have a way to replicate it? As far as the debug log goes, it seems like there's no space in your stash.
> > 
> > 
> > I could even record a video, but I don't think it would be comfortable to upload it here, so it's better to continue on telegram @Ultra119
> 
> Is your inventory full?

https://pastebin.com/YX8Ds919
https://youtu.be/6nlCz0iJyec

**Comment by Ultra119** [comment]
> I would consider redoing the server installation. It came to my attention people were using this mysterious . The tutorial has been updated.`mtga-install`

I used the npm install

**Comment by ae-King** [comment]
> > I would consider redoing the server installation. It came to my attention people were using this mysterious . The tutorial has been updated.`mtga-install`
> 
> I used the npm install

Try my branch with a fresh account, see if you get the same results.

**Comment by Ultra119** [comment]
> Try my branch with a fresh account, see if you get the same results.

now works, with all items

**Comment by Ultra119** [comment]
By the way, there is a question. Is the coop working?

**Comment by Nehaxfr** [comment]
> By the way, there is a question. Is the coop working?

Coop never worked and probably wont ever work. The dude that was working on the coop module rage quited the singleplayer tarkov community.
