### ISSUE TITLE
Game Closes on Startup

### ISSUE THREAD

**Issue by perryismyname** [Make-Tarkov-Great-Again/MTGA-Backend#94]
I tried downloading yesterday, I followed the wiki section and got everything almost running. The client side was not difficult to set up but that is where I believe I am having problems as the server launches displays "MTGA" says "server listening at ...443" and "profile database loaded" but the app closes itself upon launch (run as admin) just at it does in step 5 of client setup.

**Comment by ae-King** [comment]
It is likely you forgot to install the binaries, or installed them incorrectly.

**Comment by perryismyname** [comment]
The binaries is the part I did not know how to set up for sure. It did not mention them in the Wiki, I just dragged them into the games root folder after I completed everything else. I am not super tech savvy so I am surprised I have even made it to this point. After reading back over it I assume I am missing the "compiling" section. I do not understand what the first bullet point under the "how to compile?" means in the binaries page. Running the command in the second bullet point spits out 

```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

I might need to wait for a video tutorial some day.

**Comment by ae-King** [comment]
I am advising you to re-read that section.

**Comment by SlejmUr** [comment]
Also Install the .NET SDK

**Comment by perryismyname** [comment]
Downgrading the battlestate version as well as not attempting to "compile" code fixed this.
